#PROYECTO - ANÁLISIS DE CRÍTICAS DE PELICULAS FILMAFFINITY EN ESPAÑOL

El sentimiento de análisis (sentiment analysis en inglés) es una subdisciplina del campo procesamiento del lenguaje natural (NLP en inglés) bastante común y que nos permite identificar la opinión emocional que hay detrás de un texto, es decir, si es positivo, negativo o neutro.

Como podéis imaginaros, esta técnica tiene innumerables aplicaciones debido a su gran utilidad. Por ejemplo, el análisis de sentimientos podría ayudar a una empresa a entender el sentimiento que provoca su marca, producto o servicio aplicándolo a los tweets en los que son mencionados.

Para este tutorial nos hemos basado en el ejemplo práctico que aparece en el capítulo 8 del fantástico libro Python Machine Learning, donde utilizan 50.000 críticas de películas altamente polares del sitio web IMDb para construir un clasificador capaz de identificar si una crítica de una película tiene un sentimiento positivo o negativo.

Vamos a utilizar un conjunto de datos consistente en 4.800 críticas de usuarios y sus puntuaciones correspondientes de la página web de filmaffinity. Filmaffinity es una web de recomendación de películas y series donde los usuarios pueden escribir y compartir sus propias reseñas de cada película junto con una valoración numérica que puede ir del 1 al 10.

---
# Librerías a utilizar

In [3]:
import nltk
nltk.download('stopwords') #descargar los recursos de nltk

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [4]:
#import mysql.connector
import pandas as pd
import numpy as np
#import json
import re
#import eli5
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.tokenize import ToktokTokenizer
#from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix

In [6]:
# Cargamos el fichero con las críticas y su puntuación
#df = pd.read_csv("/content/sample_data/proyecto.csv", encoding='utf8')

df = pd.read_table('/content/sample_data/proyecto.csv', sep='\|\|', header=0, engine='python')
df.sample(5)

# Mostramos las primeras 5 observaciones
df.head()

,film_name,gender,film_avg_rate,review_rate,review_title,review_text
0,Ocho apellidos vascos,Comedia,"6,0",3.0,OCHO APELLIDOS VASCOS...Y NINGÚN NOMBRE PROPIO,La mayor virtud de esta película es su existen...
1,Ocho apellidos vascos,Comedia,"6,0",2.0,El perro verde,"No soy un experto cinéfilo, pero pocas veces m..."
2,Ocho apellidos vascos,Comedia,"6,0",2.0,Si no eres de comer mierda... no te comas esta...,Si no eres un incondicional del humor estilo T...
3,Ocho apellidos vascos,Comedia,"6,0",2.0,Aida: The movie,"No sé qué está pasando, si la gente se deja ll..."
4,Ocho apellidos vascos,Comedia,"6,0",2.0,UN HOMBRE SOLO (Julio Iglesias 1987),"""Pero cuando amanece,y me quedo solo,siento en..."

In [7]:
# Creamos una variable con el sentimiento
# Si puntuación > 6 -> 1
# Si puntuación < 5 -> 0
df['sentiment'] = np.where(df['review_rate'] > 6, 1, 0)

# Eliminamos las variables nota y url
df.drop(columns=["film_name","gender", "film_avg_rate", "review_rate", "review_title"], inplace=True)

df.head()

                                         review_text  sentiment
0  La mayor virtud de esta película es su existen...          0
1  No soy un experto cinéfilo, pero pocas veces m...          0
2  Si no eres un incondicional del humor estilo T...          0
3  No sé qué está pasando, si la gente se deja ll...          0
4  "Pero cuando amanece,y me quedo solo,siento en...          0

---
# Limpieza y preprocesamiento

In [8]:
tokenizer = ToktokTokenizer()
STOPWORDS = set(stopwords.words("spanish"))
stemmer = SnowballStemmer("spanish")

def limpiar_texto(texto):
    """
    Función para realizar la limpieza de un texto dado.
    """
    # Eliminamos los caracteres especiales
    texto = re.sub(r'\W', ' ', str(texto))
    # Eliminado las palabras que tengo un solo caracter
    texto = re.sub(r'\s+[a-zA-Z]\s+', ' ', texto)
    # Sustituir los espacios en blanco en uno solo
    texto = re.sub(r'\s+', ' ', texto, flags=re.I)
    # Eliminar numeros
    texto = re.sub(r'[0-9]+', '', texto)
    # Convertimos textos a minusculas
    texto = texto.lower()
    return texto

In [9]:
def filtrar_stopword_digitos(tokens):
    """
    Filtra stopwords y digitos de una lista de tokens.
    """
    return [token for token in tokens if token not in STOPWORDS
            and not token.isdigit()]

In [10]:
def stem_palabras(tokens):
    """
    Reduce cada palabra de una lista dada a su raíz.
    """
    return [stemmer.stem(token) for token in tokens]

In [11]:
def tokenize(texto):
    """
    Método encargado de realizar la limpieza y preprocesamiento de un texto
    """
    text_cleaned = limpiar_texto(texto)
    tokens = [word for word in tokenizer.tokenize(text_cleaned) if len(word) > 1]
    tokens = filtrar_stopword_digitos(tokens)
    stems = stem_palabras(tokens)
    return stems

In [12]:
df_1 = df.copy()
df_val1=df_1[df_1['sentiment']==1]
df_val1

                                            review_text  sentiment
5     La llegada de Rafa a Euskadi es como ponerse a...          1
21    Divertidísima película la de Emilio Martínez-L...          1
23    ¿Cuantas comedias americanas de "éxito" he vis...          1
27    Ahora que el cine está más barato, merece la p...          1
31    Tanto criticar el despilfarro cultural en el c...          1
...                                                 ...        ...
8591  Qué decir de un director tan acertado como Alb...          1
8593  Buenísimo.., salgo encantado. Digna de ver, de...          1
8594  Me ha parecido una obra maestra de principio a...          1
8596  Lleva un tiempo el cine español sorprendiéndom...          1
8598  Buena no, lo siguiente. Por fin un film serio ...          1

[3920 rows x 2 columns]

In [13]:
#*****************************************************
df_val0=df_1[df_1['sentiment']==0]
#df_val0=df_val3.sample(n = 400)
df_val0

                                            review_text  sentiment
0     La mayor virtud de esta película es su existen...          0
1     No soy un experto cinéfilo, pero pocas veces m...          0
2     Si no eres un incondicional del humor estilo T...          0
3     No sé qué está pasando, si la gente se deja ll...          0
4     "Pero cuando amanece,y me quedo solo,siento en...          0
...                                                 ...        ...
8597  Esto es lo que consideramos bueno?Pagar una en...          0
8599  Me esperaba mucho, pero que mucho, más.Guión m...          0
8600  De mal cuerpo como sensación al finalizar, de ...          0
8601  Los que han añadido comentarios os lo han dich...          0
8602  Fui a ver esta película de cine con entusiasmo...          0

[4683 rows x 2 columns]

In [14]:
df_final=pd.concat([df_val1,df_val0])
df_final

                                            review_text  sentiment
5     La llegada de Rafa a Euskadi es como ponerse a...          1
21    Divertidísima película la de Emilio Martínez-L...          1
23    ¿Cuantas comedias americanas de "éxito" he vis...          1
27    Ahora que el cine está más barato, merece la p...          1
31    Tanto criticar el despilfarro cultural en el c...          1
...                                                 ...        ...
8597  Esto es lo que consideramos bueno?Pagar una en...          0
8599  Me esperaba mucho, pero que mucho, más.Guión m...          0
8600  De mal cuerpo como sensación al finalizar, de ...          0
8601  Los que han añadido comentarios os lo han dich...          0
8602  Fui a ver esta película de cine con entusiasmo...          0

[8603 rows x 2 columns]

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_final, *['sentiment'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_final, *['sentiment'], **{})
chart

In [17]:
df_final[["review_text"]].head()

                                          review_text
5   La llegada de Rafa a Euskadi es como ponerse a...
21  Divertidísima película la de Emilio Martínez-L...
23  ¿Cuantas comedias americanas de "éxito" he vis...
27  Ahora que el cine está más barato, merece la p...
31  Tanto criticar el despilfarro cultural en el c...

In [21]:
tokenizer = ToktokTokenizer()

texto = df_final[["review_text"]].head()[0:1].to_numpy()[0][0]
texto_limpio = limpiar_texto(texto)
tokens = [word for word in tokenizer.tokenize(texto_limpio) if len(word) > 1]
tokens = filtrar_stopword_digitos(tokens)
stems = stem_palabras(tokens)
stems

['lleg',
 'raf',
 'euskadi',
 'pon',
 'ver',
 'apell',
 'vasc',
 'ira',
 'buen',
 'pues',
 'afortun',
 'pelicul',
 'lej',
 'mied',
 'lej',
 'convencional',
 'tem',
 'tabu',
 'hac',
 'pued',
 'parec',
 'previs',
 'tipic',
 'comedi',
 'romant',
 'enred',
 'ambient',
 'grand',
 'contrast',
 'conoc',
 'cultur',
 'lengu',
 'clim',
 'etc',
 'etc',
 'encim',
 'agreg',
 'tradicion',
 'tan',
 'dispar',
 'vam',
 'dec',
 'coñ',
 'tipic',
 'comedi',
 'tont',
 'romant',
 'enred',
 'consab',
 'tont',
 'siempr',
 'amig',
 'funcion',
 'funcion',
 'result',
 'quier',
 'descubr',
 'sab',
 'quier',
 'nadi',
 'salg',
 'teoriz',
 'conflict',
 'vasc',
 'quier',
 'cuent',
 'lej',
 'teor',
 'quier',
 'calor',
 'herrik',
 'tabern',
 'chist',
 'tont',
 'escen',
 'previs',
 'gent',
 'call',
 'mar',
 'entonc',
 'pued',
 'dar',
 'cuent',
 'just',
 'mejor',
 'cualid',
 'pelicul',
 'verd',
 'much',
 'import',
 'absolut',
 'sencillez',
 'ningun',
 'joy',
 'cin',
 'esplend',
 'revel',
 'autent',
 'bombaz',
 'pues',
 'mejor',
 'mejor',
 'secret',
 'pelicul',
 'hech',
 'gan',
 'agrad',
 'fotograf',
 'estupend',
 'pued',
 'ser',
 'form',
 'paisaj',
 'tan',
 'hermos',
 'cualid',
 'mon',
 'tem',
 'tan',
 'sencill',
 'deca',
 'ningun',
 'moment',
 'moment',
 'esplend',
 'personaj',
 'dentr',
 'logic',
 'domin',
 'accion',
 'natural',
 'espontan',
 'dign',
 'reconoc',
 'igual',
 'choqu',
 'gener',
 'hac',
 'sup',
 'creibl',
 'emocion',
 'pelin',
 'agrad',
 'siempr',
 'sencillez',
 'delant',
 'simplez',
 'si',
 'quier',
 'conflict',
 'padr',
 'hij',
 'unic',
 'histori',
 'ven',
 'atras',
 'ahi',
 'qued',
 'busqu',
 'tres',
 'pies',
 'gat',
 'hag',
 'list',
 'teoriz',
 'guion',
 'pobr',
 'produccion',
 'previsibil',
 'escen',
 'raic',
 'vasc',
 'tierr',
 'llen',
 'raic',
 'top',
 'roedor',
 'pedigr',
 'algun',
 'meriend',
 'descar',
 'sab',
 'lech',
 'busqu',
 'apell',
 'vasc',
 'buen',
 'ser',
 'chic',
 'vasc',
 'gust',
 'qued',
 'remedi',
 'cre',
 'pas',
 'buen',
 'rat',
 'pas',
 'pij',
 'kal',
 'borroc',
 'progr',
 'pues',
 'problem']

# Dividimos los datos en train y test

In [23]:
X = df_final.review_text
y = df_final.sentiment
# SEPARAR EN 70% Y 30%
X_train_txt, X_test_txt, y_train, y_test = train_test_split(X, y, test_size=0.33,
                                                    stratify=y, random_state=42)

In [24]:
X_test_txt

7270    Se le dio mucha caña al Orfanato por considera...
7280    La película, para quien no la haya visto, es b...
3548    Desencanta y aún más si se ha leído a Perez Re...
5442    Recuerdo ver esta película un día de enero con...
1716    Cómo influyen las malas críticas. Aunque en el...
                              ...
4688    Es una película muy divertida y fantástica.Se ...
1181    Desde el inicio hasta el final, el orfanato es...
3946    Nos llega esta “Celda 211” después del éxito d...
8119    Una de las peores películas que he visto en lo...
1022    No era de extrañar que, tras el insólito y des...
Name: review_text, Length: 2839, dtype: object

In [25]:
# Comprobamos que train y test contienen el mismo porcentaje de cada clase en y
print(len(y_train)/len(y)) #verificamos que la data de entrenamiento sea de 67%
print(len(y_test)/len(y)) #verificamos que la data de test sea de 33%

#comprobamos balance de datos
print(len(y_train[y_train==1])/len(y_train)) #verificamos que los datos esten balanceados por categoria dentro del entrenamiento
print(len(y_test[y_test==1])/len(y_test)) #verificamos que los datos esten balanceados por categoria dentro del test

0.6699988376147855
0.3300011623852145
0.45558639833448994
0.45579429376541036

In [26]:
tfidf = TfidfVectorizer(
    tokenizer=tokenize,
    max_features=20000)

tfidf.fit(X_train_txt)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

TfidfVectorizer(max_features=20000,
                tokenizer=<function tokenize at 0x791550d71240>)

In [27]:
X_train = tfidf.transform(X_train_txt)
X_test = tfidf.transform(X_test_txt)
print(X_train.shape)
print(X_test.shape)

(5764, 20000)
(2839, 20000)

In [28]:
X_train

<5764x20000 sparse matrix of type '<class 'numpy.float64'>'
	with 505758 stored elements in Compressed Sparse Row format>

#CODIFICACIÓN

In [29]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train_txt)
MODO='binary' #fidf,freq,binary,count,tfidf
prueba_X_train = tokenizer.texts_to_matrix(X_train_txt, mode=MODO)

In [30]:
print(tokenizer.word_index.items())

dict_items([('de', 1), ('que', 2), ('la', 3), ('y', 4), ('en', 5), ('el', 6), ('a', 7), ('no', 8), ('es', 9), ('un', 10), ('una', 11), ('los', 12), ('se', 13), ('con', 14), ('lo', 15), ('por', 16), ('película', 17), ('del', 18), ('las', 19), ('más', 20), ('pero', 21), ('como', 22), ('para', 23), ('su', 24), ('me', 25), ('al', 26), ('muy', 27), ('esta', 28), ('todo', 29), ('o', 30), ('si', 31), ('cine', 32), ('ha', 33), ('sin', 34), ('bien', 35), ('le', 36), ('historia', 37), ('ya', 38), ('sus', 39), ('ni', 40), ('está', 41), ('nos', 42), ('son', 43), ('tiene', 44), ('ser', 45), ('porque', 46), ('este', 47), ('hay', 48), ('mejor', 49), ('ver', 50), ('te', 51), ('tan', 52), ('mi', 53), ('hace', 54), ('mucho', 55), ('algo', 56), ('eso', 57), ('nada', 58), ('poco', 59), ('gran', 60), ('sobre', 61), ('aunque', 62), ('personajes', 63), ('cuando', 64), ('películas', 65), ('todos', 66), ('español', 67), ('he', 68), ('guión', 69), ('también', 70), ('final', 71), ('menos', 72), ('puede', 73), ('parece', 74), ('actores', 75), ('vez', 76), ('así', 77), ('hacer', 78), ('dos', 79), ('buena', 80), ('parte', 81), ('desde', 82), ('sí', 83), ('hasta', 84), ('personaje', 85), ('entre', 86), ('tanto', 87), ('uno', 88), ('director', 89), ('ese', 90), ('han', 91), ('bastante', 92), ('hecho', 93), ('siempre', 94), ('decir', 95), ('esto', 96), ('film', 97), ('sea', 98), ('yo', 99), ('creo', 100), ('española', 101), ('otro', 102), ('otra', 103), ('donde', 104), ('pues', 105), ('visto', 106), ('vida', 107), ('buen', 108), ('va', 109), ('e', 110), ('esa', 111), ('comedia', 112), ('momento', 113), ('qué', 114), ('unos', 115), ('mal', 116), ('escenas', 117), ('cada', 118), ('da', 119), ('solo', 120), ('sólo', 121), ('años', 122), ('mismo', 123), ('toda', 124), ('momentos', 125), ('están', 126), ('espectador', 127), ('papel', 128), ('españa', 129), ('amenábar', 130), ('primera', 131), ('otros', 132), ('aquí', 133), ('trama', 134), ('era', 135), ('torrente', 136), ('bueno', 137), ('mundo', 138), ('tiempo', 139), ('sido', 140), ('además', 141), ('muchos', 142), ('fin', 143), ('casi', 144), ('algunos', 145), ('verdad', 146), ('cosas', 147), ('veces', 148), ('gente', 149), ('haber', 150), ('forma', 151), ('cinta', 152), ('cuenta', 153), ('humor', 154), ('peli', 155), ('cierto', 156), ('peor', 157), ('les', 158), ('falta', 159), ('trabajo', 160), ('sino', 161), ('todas', 162), ('demasiado', 163), ('verla', 164), ('tipo', 165), ('caso', 166), ('escena', 167), ('terror', 168), ('incluso', 169), ('fue', 170), ('después', 171), ('cosa', 172), ('punto', 173), ('obra', 174), ('protagonista', 175), ('tampoco', 176), ('ella', 177), ('crítica', 178), ('hacen', 179), ('realidad', 180), ('lado', 181), ('deja', 182), ('otras', 183), ('nunca', 184), ('manera', 185), ('claro', 186), ('ahora', 187), ('muchas', 188), ('fotografía', 189), ('mas', 190), ('mí', 191), ('ante', 192), ('aún', 193), ('público', 194), ('segura', 195), ('gracia', 196), ('actor', 197), ('mala', 198), ('género', 199), ('ellos', 200), ('mejores', 201), ('cualquier', 202), ('resulta', 203), ('queda', 204), ('consigue', 205), ('duda', 206), ('luego', 207), ('nuestro', 208), ('cámara', 209), ('ello', 210), ('realmente', 211), ('cual', 212), ('pasar', 213), ('día', 214), ('antes', 215), ('país', 216), ('grandes', 217), ('tal', 218), ('alguna', 219), ('interpretaciones', 220), ('minutos', 221), ('durante', 222), ('había', 223), ('podría', 224), ('argumento', 225), ('tienen', 226), ('él', 227), ('sentido', 228), ('algunas', 229), ('unas', 230), ('interpretación', 231), ('resto', 232), ('reparto', 233), ('interesante', 234), ('principio', 235), ('miedo', 236), ('igual', 237), ('haya', 238), ('embargo', 239), ('quien', 240), ('ningún', 241), ('nivel', 242), ('pena', 243), ('fuera', 244), ('pesar', 245), ('tener', 246), ('demás', 247), ('javier', 248), ('tema', 249), ('nadie', 250), ('único', 251), ('algún', 252), ('quizás', 253), ('guerra', 254), ('tras', 255), ('buenos', 256), ('éxito', 257), ('situaciones', 258), ('lugar', 259), ('original', 260), ('buenas', 261), ('misma', 262), ('ritmo', 263), ('pasa', 264), ('ahí', 265), ('siendo', 266), ('nota', 267), ('críticas', 268), ('esos', 269), ('tres', 270), ('dirección', 271), ('mayor', 272), ('sabe', 273), ('vista', 274), ('música', 275), ('estos', 276), ('calidad', 277), ('pantalla', 278), ('estar', 279), ('dentro', 280), ('personas', 281), ('sé', 282), ('dicho', 283), ('cómo', 284), ('general', 285), ('dar', 286), ('actuación', 287), ('llega', 288), ('imposible', 289), ('familia', 290), ('trata', 291), ('sensación', 292), ('gracias', 293), ('año', 294), ('hora', 295), ('rato', 296), ('protagonistas', 297), ('cuanto', 298), ('gusta', 299), ('ambientación', 300), ('real', 301), ('malo', 302), ('tensión', 303), ('opinión', 304), ('época', 305), ('rovira', 306), ('almodóvar', 307), ('acción', 308), ('ir', 309), ('resultado', 310), ('ejemplo', 311), ('pasado', 312), ('actuaciones', 313), ('estilo', 314), ('segunda', 315), ('planos', 316), ('efectos', 317), ('hubiera', 318), ('luis', 319), ('excelente', 320), ('nuevo', 321), ('amor', 322), ('santiago', 323), ('apellidos', 324), ('esas', 325), ('idea', 326), ('bayona', 327), ('tópicos', 328), ('diálogos', 329), ('entretenida', 330), ('sigue', 331), ('tosar', 332), ('tenía', 333), ('ve', 334), ('gustado', 335), ('fácil', 336), ('tenemos', 337), ('serie', 338), ('primer', 339), ('mucha', 340), ('quiere', 341), ('soy', 342), ('estamos', 343), ('merece', 344), ('ninguna', 345), ('iglesia', 346), ('vascos', 347), ('simplemente', 348), ('mientras', 349), ('drama', 350), ('producción', 351), ('goya', 352), ('van', 353), ('ésta', 354), ('dani', 355), ('poder', 356), ('encima', 357), ('5', 358), ('2', 359), ('totalmente', 360), ('dado', 361), ('viendo', 362), ('muestra', 363), ('madre', 364), ('pensar', 365), ('etc', 366), ('chistes', 367), ('pueden', 368), ('tu', 369), ('nuestra', 370), ('tengo', 371), ('puedo', 372), ('banda', 373), ('definitiva', 374), ('actriz', 375), ('genial', 376), ('saber', 377), ('estas', 378), ('juan', 379), ('mayoría', 380), ('3', 381), ('producto', 382), ('estaba', 383), ('gusto', 384), ('sería', 385), ('llegar', 386), ('hablar', 387), ('media', 388), ('rueda', 389), ('haciendo', 390), ('españoles', 391), ('alberto', 392), ('sale', 393), ('casa', 394), ('hacia', 395), ('digo', 396), ('situación', 397), ('ojos', 398), ('contra', 399), ('alguien', 400), ('belén', 401), ('medio', 402), ('esperaba', 403), ('vamos', 404), ('mujer', 405), ('contar', 406), ('sonora', 407), ('padre', 408), ('clara', 409), ('último', 410), ('allá', 411), ('problema', 412), ('especial', 413), ('saga', 414), ('quizá', 415), ('destacar', 416), ('animación', 417), ('amigos', 418), ('paso', 419), ('niños', 420), ('interés', 421), ('dice', 422), ('ganas', 423), ('será', 424), ('historias', 425), ('karra', 426), ('elejalde', 427), ('dan', 428), ('civil', 429), ('sala', 430), ('metraje', 431), ('toro', 432), ('hombre', 433), ('hoy', 434), ('veo', 435), ('lópez', 436), ('hechos', 437), ('carmen', 438), ('10', 439), ('entrega', 440), ('thriller', 441), ('volver', 442), ('talento', 443), ('mis', 444), ('divertida', 445), ('principal', 446), ('lleva', 447), ('cara', 448), ('casas', 449), ('niña', 450), ('parecido', 451), ('españolas', 452), ('debe', 453), ('alatriste', 454), ('pese', 455), ('difícil', 456), ('pocas', 457), ('grande', 458), ('mario', 459), ('spoiler', 460), ('debería', 461), ('dinero', 462), ('voy', 463), ('hizo', 464), ('posible', 465), ('dejar', 466), ('plano', 467), ('propio', 468), ('alejandro', 469), ('supuesto', 470), ('filme', 471), ('secundarios', 472), ('iba', 473), ('rec', 474), ('vaya', 475), ('ágora', 476), ('vi', 477), ('modo', 478), ('desarrollo', 479), ('estado', 480), ('conseguido', 481), ('acaba', 482), ('horas', 483), ('par', 484), ('vuelve', 485), ('largo', 486), ('fuerza', 487), ('taquilla', 488), ('hipatia', 489), ('podemos', 490), ('recomendable', 491), ('junto', 492), ('especiales', 493), ('capaz', 494), ('cabeza', 495), ('entiendo', 496), ('logra', 497), ('podía', 498), ('josé', 499), ('os', 500), ('estoy', 501), ('últimos', 502), ('importante', 503), ('niño', 504), ('ocasiones', 505), ('viene', 506), ('salir', 507), ('sociedad', 508), ('pelicula', 509), ('mujeres', 510), ('tsunami', 511), ('especialmente', 512), ('persona', 513), ('notable', 514), ('poner', 515), ('quiero', 516), ('unamuno', 517), ('llena', 518), ('seguro', 519), ('favor', 520), ('segundo', 521), ('orfanato', 522), ('maría', 523), ('malos', 524), ('detalles', 525), ('grupo', 526), ('vale', 527), ('presupuesto', 528), ('siquiera', 529), ('lago', 530), ('libros', 531), ('simple', 532), ('pueblo', 533), ('arte', 534), ('tiempos', 535), ('guillermo', 536), ('bajo', 537), ('tenido', 538), ('maestra', 539), ('partes', 540), ('1', 541), ('tanta', 542), ('muerte', 543), ('hecha', 544), ('risa', 545), ('¿qué', 546), ('reír', 547), ('amenabar', 548), ('leído', 549), ('nueva', 550), ('parecen', 551), ('mano', 552), ('aburrida', 553), ('primeros', 554), ('cuento', 555), ('propia', 556), ('papeles', 557), ('gags', 558), ('entonces', 559), ('primero', 560), ('perfectamente', 561), ('7', 562), ('fantasía', 563), ('anteriores', 564), ('boca', 565), ('hemos', 566), ('puntos', 567), ('isla', 568), ('histórico', 569), ('mismos', 570), ('actrices', 571), ('directores', 572), ('ideas', 573), ('ocho', 574), ('seguir', 575), ('creíble', 576), ('antonio', 577), ('oscar', 578), ('eran', 579), ('señor', 580), ('tenga', 581), ('hijo', 582), ('personal', 583), ('camino', 584), ('absolutamente', 585), ('cierta', 586), ('chica', 587), ('juego', 588), ('varios', 589), ('pone', 590), ('última', 591), ('guion', 592), ('contrario', 593), ('única', 594), ('mínima', 595), ('altura', 596), ('bardem', 597), ('entender', 598), ('pocos', 599), ('reconocer', 600), ('dicen', 601), ('premios', 602), ('fondo', 603), ('razón', 604), ('perfecta', 605), ('llevar', 606), ('aventuras', 607), ('demuestra', 608), ('atención', 609), ('ellas', 610), ('anterior', 611), ('lejos', 612), ('penélope', 613), ('alex', 614), ('cumple', 615), ('aparte', 616), ('temas', 617), ('sorpresa', 618), ('suspense', 619), ('hollywood', 620), ('precisamente', 621), ('haga', 622), ('funciona', 623), ('puesto', 624), ('gutiérrez', 625), ('espectadores', 626), ('risas', 627), ('todavía', 628), ('somos', 629), ('intenta', 630), ('recomiendo', 631), ('encontrar', 632), ('corazón', 633), ('habría', 634), ('parecer', 635), ('aquellos', 636), ('nosotros', 637), ('pretende', 638), ('mar', 639), ('machi', 640), ('alto', 641), ('intriga', 642), ('darle', 643), ('salvo', 644), ('puesta', 645), ('montaje', 646), ('imágenes', 647), ('celda', 648), ('social', 649), ('gustó', 650), ('conjunto', 651), ('apenas', 652), ('aspectos', 653), ('equipo', 654), ('previsible', 655), ('busca', 656), ('problemas', 657), ('dura', 658), ('empieza', 659), ('4', 660), ('ocasión', 661), ('humano', 662), ('termina', 663), ('dios', 664), ('según', 665), ('mitad', 666), ('aparece', 667), ('inteligente', 668), ('varias', 669), ('éste', 670), ('franco', 671), ('título', 672), ('nuestros', 673), ('días', 674), ('recuerdo', 675), ('luz', 676), ('aquel', 677), ('proyecto', 678), ('sean', 679), ('diferentes', 680), ('211', 681), ('nacional', 682), ('reales', 683), ('cruz', 684), ('voz', 685), ('relación', 686), ('comedias', 687), ('cameos', 688), ('watts', 689), ('pueda', 690), ('libro', 691), ('diferente', 692), ('histórica', 693), ('elementos', 694), ('lleno', 695), ('eres', 696), ('¿por', 697), ('mezcla', 698), ('vergüenza', 699), ('mostrar', 700), ('cambio', 701), ('sacar', 702), ('violencia', 703), ('mensaje', 704), ('cuatro', 705), ('sabemos', 706), ('ambiente', 707), ('policía', 708), ('tarde', 709), ('pareja', 710), ('disfrutar', 711), ('com', 712), ('8', 713), ('vasco', 714), ('millones', 715), ('fantástico', 716), ('teniendo', 717), ('crear', 718), ('objetivo', 719), ('dando', 720), ('mantiene', 721), ('siglo', 722), ('fauno', 723), ('allí', 724), ('monzón', 725), ('recuerda', 726), ('medida', 727), ('cinco', 728), ('emoción', 729), ('alguno', 730), ('impresionante', 731), ('triste', 732), ('tercera', 733), ('carlos', 734), ('espero', 735), ('esperar', 736), ('vivir', 737), ('través', 738), ('hacía', 739), ('resumen', 740), ('aun', 741), ('seguramente', 742), ('respecto', 743), ('toque', 744), ('creer', 745), ('brillante', 746), ('partir', 747), ('ofrece', 748), ('encontramos', 749), ('aspecto', 750), ('tadeo', 751), ('medios', 752), ('malamadre', 753), ('ciertos', 754), ('técnica', 755), ('debido', 756), ('fantástica', 757), ('televisión', 758), ('actual', 759), ('siento', 760), ('mierda', 761), ('espectacular', 762), ('chico', 763), ('presenta', 764), ('sonrisa', 765), ('diferencia', 766), ('pobre', 767), ('correcta', 768), ('sustos', 769), ('sentimientos', 770), ('visión', 771), ('laberinto', 772), ('tono', 773), ('quedan', 774), ('cinematográfico', 775), ('absoluto', 776), ('encuentra', 777), ('expectativas', 778), ('base', 779), ('poca', 780), ('cualquiera', 781), ('ocurre', 782), ('uso', 783), ('quién', 784), ('suerte', 785), ('increíble', 786), ('comercial', 787), ('martínez', 788), ('acento', 789), ('cabo', 790), ('nombre', 791), ('personalidad', 792), ('convierte', 793), ('supongo', 794), ('desenlace', 795), ('puro', 796), ('pareció', 797), ('fesser', 798), ('secuencias', 799), ('perfecto', 800), ('vestuario', 801), ('puedes', 802), ('has', 803), ('6', 804), ('total', 805), ('jones', 806), ('tierra', 807), ('habla', 808), ('pelis', 809), ('álex', 810), ('noche', 811), ('amigo', 812), ('acierto', 813), ('realismo', 814), ('joven', 815), ('obras', 816), ('estreno', 817), ('técnico', 818), ('pierde', 819), ('sorprendente', 820), ('magnífica', 821), ('cárcel', 822), ('naomi', 823), ('suele', 824), ('carrera', 825), ('sentir', 826), ('realista', 827), ('cabe', 828), ('jóvenes', 829), ('secuencia', 830), ('versión', 831), ('supone', 832), ('capitán', 833), ('habrá', 834), ('suficiente', 835), ('mínimo', 836), ('rodríguez', 837), ('dirigida', 838), ('euros', 839), ('vas', 840), ('aporta', 841), ('completamente', 842), ('prácticamente', 843), ('lástima', 844), ('blanca', 845), ('sinceramente', 846), ('destaca', 847), ('imaginación', 848), ('perdido', 849), ('bodrio', 850), ('basada', 851), ('ficción', 852), ('necesario', 853), ('entretenimiento', 854), ('conseguir', 855), ('manos', 856), ('imagen', 857), ('maravillosa', 858), ('elenco', 859), ('frente', 860), ('serio', 861), ('intento', 862), ('ambos', 863), ('esté', 864), ('conclusión', 865), ('originalidad', 866), ('futuro', 867), ('guionista', 868), ('enorme', 869), ('perder', 870), ('fueron', 871), ('tantas', 872), ('detective', 873), ('negro', 874), ('dejando', 875), ('digna', 876), ('sangre', 877), ('existe', 878), ('atmósfera', 879), ('fernando', 880), ('aquella', 881), ('dejado', 882), ('espera', 883), ('impecable', 884), ('visual', 885), ('oportunidad', 886), ('perfección', 887), ('hubiese', 888), ('mil', 889), ('sobretodo', 890), ('acuerdo', 891), ('mérito', 892), ('respeto', 893), ('aparecen', 894), ('chiste', 895), ('pienso', 896), ('madrid', 897), ('larga', 898), ('rodada', 899), ('ciudad', 900), ('lázaro', 901), ('hacerlo', 902), ('adentro', 903), ('sergi', 904), ('vemos', 905), ('mira', 906), ('jamás', 907), ('padres', 908), ('correcto', 909), ('tantos', 910), ('san', 911), ('minuto', 912), ('hablando', 913), ('ven', 914), ('política', 915), ('pasando', 916), ('presencia', 917), ('palabras', 918), ('alejandría', 919), ('críticos', 920), ('clase', 921), ('fuerte', 922), ('dónde', 923), ('pequeño', 924), ('caer', 925), ('ayuda', 926), ('obstante', 927), ('cama', 928), ('tus', 929), ('acabar', 930), ('fernández', 931), ('querido', 932), ('tuvo', 933), ('ramón', 934), ('viggo', 935), ('tienes', 936), ('presente', 937), ('exceso', 938), ('mención', 939), ('quienes', 940), ('sorprende', 941), ('peso', 942), ('cómico', 943), ('ammann', 944), ('interpreta', 945), ('doy', 946), ('dejan', 947), ('ciencia', 948), ('mortadelo', 949), ('podido', 950), ('ninguno', 951), ('cae', 952), ('mantener', 953), ('justo', 954), ('daniel', 955), ('nuestras', 956), ('aire', 957), ('salva', 958), ('títulos', 959), ('sonido', 960), ('cristianos', 961), ('resines', 962), ('mortensen', 963), ('divertido', 964), ('pedro', 965), ('ajena', 966), ('llorar', 967), ('hayan', 968), ('verdú', 969), ('capacidad', 970), ('pequeños', 971), ('primeras', 972), ('dudas', 973), ('personalmente', 974), ('visionado', 975), ('floja', 976), ('principales', 977), ('parecía', 978), ('romántica', 979), ('malas', 980), ('mirada', 981), ('dolor', 982), ('cuesta', 983), ('fallos', 984), ('pasan', 985), ('emociones', 986), ('comienza', 987), ('americano', 988), ('lenta', 989), ('regresión', 990), ('comienzo', 991), ('tesis', 992), ('ido', 993), ('quedado', 994), ('weisz', 995), ('intentar', 996), ('sobresaliente', 997), ('detalle', 998), ('decepción', 999), ('logrado', 1000), ('largometraje', 1001), ('verdadero', 1002), ('cultura', 1003), ('leer', 1004), ('considero', 1005), ('fui', 1006), ('secuela', 1007), ('probablemente', 1008), ('balagueró', 1009), ('clichés', 1010), ('culpa', 1011), ('salas', 1012), ('típica', 1013), ('peores', 1014), ('andaluz', 1015), ('muchísimo', 1016), ('relato', 1017), ('sabes', 1018), ('maribel', 1019), ('ciertas', 1020), ('empezar', 1021), ('habitual', 1022), ('natural', 1023), ('olvidar', 1024), ('interesantes', 1025), ('crea', 1026), ('manuela', 1027), ('atrás', 1028), ('magistral', 1029), ('prejuicios', 1030), ('esfuerzo', 1031), ('detrás', 1032), ('dramática', 1033), ('novela', 1034), ('decorados', 1035), ('clásico', 1036), ('absurdo', 1037), ('basura', 1038), ('casos', 1039), ('cutre', 1040), ('sola', 1041), ('frases', 1042), ('rosa', 1043), ('experiencia', 1044), ('inicio', 1045), ('directamente', 1046), ('emilio', 1047), ('lucha', 1048), ('mediocre', 1049), ('llegado', 1050), ('verdadera', 1051), ('taquillera', 1052), ('error', 1053), ('“el', 1054), ('cuarta', 1055), ('técnicamente', 1056), ('mente', 1057), ('valverde', 1058), ('buscar', 1059), ('industria', 1060), ('adaptación', 1061), ('mcgregor', 1062), ('internacional', 1063), ('infantil', 1064), ('alterio', 1065), ('crisis', 1066), ('sampedro', 1067), ('ponen', 1068), ('ernesto', 1069), ('vive', 1070), ('cuestión', 1071), ('producciones', 1072), ('sucesión', 1073), ('diego', 1074), ('remake', 1075), ('espacio', 1076), ('publicidad', 1077), ('presos', 1078), ('cinematográfica', 1079), ('quieren', 1080), ('policías', 1081), ('pequeña', 1082), ('línea', 1083), ('reverte', 1084), ('tragedia', 1085), ('trailer', 1086), ('argumental', 1087), ('alma', 1088), ('norte', 1089), ('aceptable', 1090), ('john', 1091), ('americana', 1092), ('diría', 1093), ('gustan', 1094), ('autor', 1095), ('estupenda', 1096), ('normal', 1097), ('particular', 1098), ('pensando', 1099), ('contexto', 1100), ('borda', 1101), ('mayores', 1102), ('escenarios', 1103), ('¿y', 1104), ('leonor', 1105), ('documental', 1106), ('especie', 1107), ('guste', 1108), ('entrar', 1109), ('sucede', 1110), ('portillo', 1111), ('llevado', 1112), ('querer', 1113), ('quiera', 1114), ('narración', 1115), ('formas', 1116), ('recursos', 1117), ('crímenes', 1118), ('butaca', 1119), ('chicas', 1120), ('cuales', 1121), ('hombres', 1122), ('tío', 1123), ('consiguen', 1124), ('transmite', 1125), ('debo', 1126), ('gritos', 1127), ('rachel', 1128), ('típico', 1129), ('salen', 1130), ('aventura', 1131), ('patrio', 1132), ('acerca', 1133), ('delante', 1134), ('sencilla', 1135), ('entrada', 1136), ('esperanza', 1137), ('guionistas', 1138), ('finalmente', 1139), ('finales', 1140), ('credibilidad', 1141), ('digno', 1142), ('universo', 1143), ('13', 1144), ('propuesta', 1145), ('fuese', 1146), ('encuentro', 1147), ('podrían', 1148), ('brutal', 1149), ('agradable', 1150), ('hacerse', 1151), ('evidente', 1152), ('desarrolla', 1153), ('familiar', 1154), ('creíbles', 1155), ('¿es', 1156), ('pura', 1157), ('propios', 1158), ('palabra', 1159), ('hawke', 1160), ('diez', 1161), ('hija', 1162),

In [31]:
prueba_X_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 1., 1.]])

In [32]:
print(X_train[:3])

  (0, 19645)	0.18205705702877095
  (0, 19620)	0.10071105472581451
  (0, 19415)	0.18559484953124333
  (0, 19369)	0.06429348021506545
  (0, 19162)	0.0869831614912786
  (0, 18494)	0.07417474496123178
  (0, 18091)	0.07006542258066598
  (0, 17509)	0.06589645886997694
  (0, 17209)	0.05489969785845686
  (0, 17105)	0.09927370226317808
  (0, 17005)	0.0983522375740612
  (0, 16764)	0.07851493208938096
  (0, 16273)	0.10137259408124184
  (0, 15390)	0.08984497576368784
  (0, 15041)	0.07965789471167335
  (0, 14603)	0.13377799816432503
  (0, 14013)	0.03551869833046281
  (0, 14007)	0.10187846866180557
  (0, 13868)	0.1495373801035758
  (0, 13738)	0.06369776316372278
  (0, 13226)	0.16603795414895317
  (0, 12075)	0.060423088840770064
  (0, 12024)	0.09238111343960546
  (0, 11824)	0.13187638720659658
  (0, 11707)	0.09922176294222662
  :	:
  (2, 12102)	0.07059482746103954
  (2, 11579)	0.06335766344324846
  (2, 11427)	0.10298917469832482
  (2, 11284)	0.07895728951411383
  (2, 10040)	0.24231853731079137
  (2, 9358)	0.19160259714958155
  (2, 9173)	0.08340394259201887
  (2, 9079)	0.33133378329105295
  (2, 8194)	0.0838895813087511
  (2, 7113)	0.10720396222641888
  (2, 6602)	0.19493645835748594
  (2, 6318)	0.15897588242861851
  (2, 6133)	0.19676322798383325
  (2, 6127)	0.16971737607032808
  (2, 4954)	0.18466438020290316
  (2, 4620)	0.16830182585789125
  (2, 3819)	0.23540236320009175
  (2, 3236)	0.07503839759946979
  (2, 1945)	0.1064176587436384
  (2, 1725)	0.13720548951958444
  (2, 1634)	0.14668338437030093
  (2, 1562)	0.15897588242861851
  (2, 908)	0.08914132683522896
  (2, 773)	0.12976154520762476
  (2, 737)	0.07763652777797231

# DESARROLLO E IMPLEMENTACION DEL MODELO

Ha llegado la hora de entrenar nuestro modelo de regresión logística para clasificar las reseñas de películas. Para ello, empleamos una estrategia grid search para realizar una búsqueda exhaustiva evaluando todas las combinaciones de parámetros con el objetivo de encontrar el mejor modelo.

Grid search es una técnica de optimización de hiperparámetros en el que se prueban todas las combinaciones posibles. A continuación, los modelos se evalúan mediante validación cruzada y se considera que el modelo con mayor accuracy (en nuestro caso) es el mejor.

Para utilizar esta estrategia, scikit learn nos proporciona el objeto GridSearchCV al que le debemos pasar como input el modelo de predicción y un diccionario con los parámetros (llamado search space) a optimizar. Este diccionario debe contener los nombres de parámetros como claves y las listas de ajustes de parámetros a probar como valores.

En nuestro caso queremos probar distintos valores del parámetro C, que añade regularización al modelo para reducir el overfitting, y el parámetro penalty para probar distintos tipos de regularización (Lasso y Ridge en nuestro caso).

In [33]:
# Diccionario con nombres de parámetros como claves y listas
# de ajustes de parámetros a probar como valores
parameters = {'penalty':('l1', 'l2'), 'C':[100, 10, 1.0, 0.1, 0.01]}

# Modelo de Regresión logistica
lr = LogisticRegression(random_state=42, solver='liblinear')

In [34]:
# Objecto KFold para dividir un conjunto de datos en N bloques
cv = KFold(n_splits=4, shuffle=True, random_state=42)

In [35]:
# GridSearchCV para la búsqueda de los mejores parámetros
clf = GridSearchCV(lr, parameters,
                   scoring='accuracy',
                   cv=cv,
                   refit=True,
                   verbose=2,
                   n_jobs=-1)

In [42]:
clf.fit(X_train, y_train)

Fitting 4 folds for each of 10 candidates, totalling 40 fits

GridSearchCV(cv=KFold(n_splits=4, random_state=42, shuffle=True),
             estimator=LogisticRegression(random_state=42, solver='liblinear'),
             n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ('l1', 'l2')},
             scoring='accuracy', verbose=2)

In [43]:
print('Mejor combinación de parámetros: %s ' % clf.best_params_)
print('CV Accuracy: %.3f' % clf.best_score_)

Mejor combinación de parámetros: {'C': 1.0, 'penalty': 'l2'}
CV Accuracy: 0.795

In [45]:
best_clf = clf.best_estimator_
print('Test Accuracy: %.3f' % best_clf.score(X_test, y_test))

Test Accuracy: 0.805

<img src="https://empresas.blogthinkbig.com/wp-content/uploads/2020/09/matriz.jpg" alt="Simply Easy Learning" width="400"
         height="200">

In [46]:
y_pred = best_clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[1317,  228],
       [ 327,  967]])

In [47]:
!pip install eli5

Collecting eli5
  Downloading eli5-0.13.0.tar.gz (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.2/216.2 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: attrs>17.1.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (23.1.0)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (3.1.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from eli5) (1.10.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from eli5) (1.16.0)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.10/dist-packages (from eli5) (1.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from eli5) (0.20.1)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from eli5) (0.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=3.0.0->eli5) (2.1.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->eli5) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->eli5) (3.2.0)
Building wheels for collected packages: eli5
  Building wheel for eli5 (setup.py) ... done
  Created wheel for eli5: filename=eli5-0.13.0-py2.py3-none-any.whl size=107719 sha256=edd4dbd1ed8761bbe50be056d234624ebfc583fc52ad06a1a6ba327a33dc11fc
  Stored in directory: /root/.cache/pip/wheels/b8/58/ef/2cf4c306898c2338d51540e0922c8e0d6028e07007085c0004
Successfully built eli5
Installing collected packages: eli5
Successfully installed eli5-0.13.0

In [48]:
import eli5

eli5.show_weights(estimator=best_clf,
                  feature_names= list(tfidf.get_feature_names_out()),
                 top=(10, 10))

# Predicción de nuevos datos

In [64]:
tokenizer = ToktokTokenizer()

opinion=["la pelicula me desagrada"]
X_prueba = tfidf.transform(opinion)
print(X_prueba.shape)

(1, 20000)

In [65]:
best_clf.predict(X_prueba)

array([0])

---